#!/bin/bash -e

export DOCKER_WAIT_TIMEOUT=${DOCKER_WAIT_TIMEOUT:-60}
export DOCKER_WAIT_SLEEPTIME=${DOCKER_WAIT_SLEEPTIME:-0.5}

test -n "${DOCKER_NAME}"

timeout ${DOCKER_WAIT_TIMEOUT} bash -c 'until [ "$(docker inspect -f {{.State.Running}} ${DOCKER_NAME})" == "true" ]; do sleep "${DOCKER_WAIT_SLEEPTIME}"; done'
