#!/bin/bash -e

# Check that DOCKER_NAME is set
if [ -z "${DOCKER_NAME}" ]; then
	>&2 echo "DOCKER_NAME must be set in the environment to use $0"
	>&2 echo "Set DOCKER_NAME to the name of the container"
	exit 1
fi

# Get the container's PID
DOCKER_PID="$(docker inspect -f {{.State.Pid}} ${DOCKER_NAME})"

# Setup the netns
NETNS_DIR=/var/run/netns
mkdir -p ${NETNS_DIR}
ln -sf /proc/${DOCKER_PID}/ns/net ${NETNS_DIR}/${DOCKER_PID}

# Execute the given command inside the containers netns
exec ip netns exec ${DOCKER_PID} "$@"
